# -*- coding: utf-8 -*-
"""finance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FsxUVBX1xdbR9vOaBbLtLKw829f8RBl0
"""

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import os # Import the os module

# ─────────────────────────────────────────────
# 1. LOAD & TAG EACH YEAR
# ─────────────────────────────────────────────
years = [2014, 2015, 2016, 2017, 2018]
frames = []

for yr in years:
    df = pd.read_csv(f'{yr}_Financial_Data.csv', index_col=0)
    df.index.name = 'Ticker'
    df = df.reset_index()

    # Rename the dynamic price-var column to a standard name
    price_var_cols = [c for c in df.columns if 'PRICE VAR' in c.upper()]
    if price_var_cols:
        df.rename(columns={price_var_cols[0]: 'Annual_Price_Change_Pct'}, inplace=True)

    df['Year'] = yr
    frames.append(df)

# ─────────────────────────────────────────────
# 2. MERGE INTO ONE FLAT TABLE
# ─────────────────────────────────────────────
combined = pd.concat(frames, ignore_index=True)
combined['Year'] = combined['Year'].astype(int)

print(f"Raw combined shape: {combined.shape}")

# ─────────────────────────────────────────────
# 3. DATA CLEANING
# ─────────────────────────────────────────────

# 3a. Drop rows where Ticker is blank/null
combined = combined[combined['Ticker'].notna() & (combined['Ticker'].str.strip() != '')]

# 3b. Drop pure-duplicate rows
combined = combined.drop_duplicates(subset=['Ticker', 'Year'])

# 3c. Class column: keep only 0/1, drop ambiguous
combined = combined[combined['Class'].isin([0, 1])]
combined['Class'] = combined['Class'].astype(int)

# 3d. Coerce all numeric columns (everything except Ticker, Sector, Class, Year)
meta_cols = ['Ticker', 'Year', 'Sector', 'Class']
numeric_cols = [c for c in combined.columns if c not in meta_cols]
for col in numeric_cols:
    combined[col] = pd.to_numeric(combined[col], errors='coerce')

# 3e. Remove rows with no financial data at all (all numeric cols null)
combined = combined.dropna(subset=numeric_cols, how='all')

# 3f. Cap extreme outliers at 1st / 99th percentile per numeric column
# (keeps data realistic for viz without deleting rows)
for col in numeric_cols:
    if col == 'Annual_Price_Change_Pct':
        continue  # keep raw for analysis
    p1 = combined[col].quantile(0.01)
    p99 = combined[col].quantile(0.99)
    combined[col] = combined[col].clip(lower=p1, upper=p99)

print(f"Clean combined shape: {combined.shape}")

# ─────────────────────────────────────────────
# 4. FEATURE ENGINEERING  (Tableau-ready columns)
# ─────────────────────────────────────────────

# Profitability tier
def profit_tier(margin):
    if pd.isna(margin): return 'Unknown'
    if margin >= 0.20: return 'High (≥20%)'
    if margin >= 0.10: return 'Medium (10-20%)'
    if margin >= 0:    return 'Low (0-10%)'
    return 'Negative'

combined['Profit_Margin_Tier'] = combined['Net Profit Margin'].apply(profit_tier)

# Leverage bucket
def leverage_bucket(de):
    if pd.isna(de): return 'Unknown'
    if de < 0.5:  return 'Conservative (<0.5x)'
    if de < 1.0:  return 'Moderate (0.5-1x)'
    if de < 2.0:  return 'Elevated (1-2x)'
    return 'High (>2x)'

combined['Leverage_Bucket'] = combined['Debt to Equity'].apply(leverage_bucket)

# Growth label based on Revenue Growth
def growth_label(g):
    if pd.isna(g): return 'Unknown'
    if g > 0.15:  return 'High Growth (>15%)'
    if g > 0.05:  return 'Moderate Growth (5-15%)'
    if g >= 0:    return 'Flat (0-5%)'
    return 'Declining'

combined['Revenue_Growth_Label'] = combined['Revenue Growth'].apply(growth_label)

# Stock performance label
def perf_label(p):
    if pd.isna(p): return 'Unknown'
    if p > 20:   return 'Strong Outperformer (>20%)'
    if p > 5:    return 'Outperformer (5-20%)'
    if p >= -5:  return 'Neutral (-5% to 5%)'
    if p >= -20: return 'Underperformer (-20% to -5%)'
    return 'Heavy Decline (<-20%)'

combined['Performance_Label'] = combined['Annual_Price_Change_Pct'].apply(perf_label)

# Class label
combined['Class_Label'] = combined['Class'].map({1: 'Positive Return', 0: 'Negative/Flat Return'})

# ─────────────────────────────────────────────
# 5. KEY METRICS SUBSET  (Tableau focus table)
# ─────────────────────────────────────────────
key_metrics = [
    'Ticker', 'Year', 'Sector', 'Class', 'Class_Label',
    'Annual_Price_Change_Pct', 'Performance_Label',

    # Income Statement
    'Revenue', 'Revenue Growth', 'Gross Profit', 'Operating Income',
    'Net Income', 'EPS', 'EPS Diluted',

    # Margins
    'Gross Margin', 'EBIT Margin', 'Net Profit Margin', 'EBITDA Margin',
    'Profit_Margin_Tier', 'Revenue_Growth_Label',

    # Cash Flow
    'Operating Cash Flow', 'Free Cash Flow', 'Capital Expenditure',
    'Free Cash Flow margin',

    # Balance Sheet
    'Total assets', 'Total liabilities', 'Total shareholders equity',
    'Cash and short-term investments', 'Total debt', 'Net Debt',

    # Valuation
    'Market Cap', 'Enterprise Value', 'PE ratio', 'Price to Sales Ratio',
    'priceToBookRatio', 'Enterprise Value over EBITDA',

    # Profitability / Returns
    'returnOnAssets', 'returnOnEquity', 'returnOnCapitalEmployed', 'ROIC',

    # Leverage / Liquidity
    'Debt to Equity', 'Debt to Assets', 'currentRatio', 'quickRatio',
    'Leverage_Bucket', 'interestCoverage',

    # Per Share
    'Revenue per Share', 'Net Income per Share', 'Book Value per Share',
    'Dividend per Share', 'dividendYield',

    # Growth rates
    'Gross Profit Growth', 'Net Income Growth', 'EPS Growth',
    'Operating Cash Flow growth', 'Free Cash Flow growth',
]

# Keep only columns that exist
key_metrics = [c for c in key_metrics if c in combined.columns]
tableau_df = combined[key_metrics].copy()
selected_companies = [
    'AAPL','MSFT','NVDA','JPM','GS',
    'KO','PEP','PG','JNJ','PFE','XOM'
]

tableau_df = tableau_df[tableau_df['Ticker'].isin(selected_companies)]
print(f"Tableau export shape: {tableau_df.shape}")
print(f"Years: {sorted(tableau_df['Year'].unique())}")
print(f"Sectors: {sorted(tableau_df['Sector'].dropna().unique())}")
print(f"Total unique tickers: {tableau_df['Ticker'].nunique()}")
print(f"\nClass distribution:\n{tableau_df['Class_Label'].value_counts()}")
print(f"\nNull % in key cols:")
key_check = ['Annual_Price_Change_Pct','Net Profit Margin','returnOnEquity','PE ratio','Debt to Equity']
print(tableau_df[key_check].isnull().mean().round(3))

# ─────────────────────────────────────────────
# 6. EXPORT
# ─────────────────────────────────────────────
out_full = '/content/outputs/SP500_2014_2018_Full_Clean.csv'
out_key  = '/content/outputs/SP500_2014_2018_Tableau_Ready.csv'

# Ensure the output directory exists
output_dir = os.path.dirname(out_full)
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

combined.to_csv(out_full, index=False)
tableau_df.to_csv(out_key, index=False)

print(f"\n✅ Full dataset saved  → {out_full}  ({combined.shape[0]} rows × {combined.shape[1]} cols)")
print(f"✅ Tableau dataset saved → {out_key}  ({tableau_df.shape[0]} rows × {tableau_df.shape[1]} cols)")

# ════════════════════════════════════════════════════════════════
#  S&P 500 Financial Data  |  2014–2018  |  Google Colab Script
#  Steps: Mount Drive → Load → Clean → Engineer → Filter → Export
# ════════════════════════════════════════════════════════════════

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import os # Import the os module
from google.colab import files # Import files module for Colab download functionality

# ─────────────────────────────────────────────
# 1. LOAD & TAG EACH YEAR
# ─────────────────────────────────────────────
years = [2014, 2015, 2016, 2017, 2018]
frames = []

for yr in years:
    df = pd.read_csv(f'{yr}_Financial_Data.csv', index_col=0)
    df.index.name = 'Ticker'
    df = df.reset_index()
# ─────────────────────────────────────────────────────────────────
# STEP 0 — Mount Google Drive
# Upload your 5 CSV files to a folder in Drive before running this
# ─────────────────────────────────────────────────────────────────


    # Standardise the price-var column (it_changes name each year)
    price_var_cols = [c for c in df.columns if 'PRICE VAR' in c.upper()]
    if price_var_cols:
        df.rename(columns={price_var_cols[0]: 'Annual_Price_Change_Pct'}, inplace=True)

    df['Year'] = yr
    frames.append(df)
    print(f"  {yr} loaded — {len(df)} rows")

combined = pd.concat(frames, ignore_index=True)
combined['Year'] = combined['Year'].astype(int)
print(f"\nRaw combined: {combined.shape[0]} rows × {combined.shape[1]} cols")


# ─────────────────────────────────────────────────────────────────
# STEP 2 — DATA CLEANING
# ─────────────────────────────────────────────────────────────────

# Remove blank tickers
combined = combined[combined['Ticker'].notna() & (combined['Ticker'].str.strip() != '')]

# Remove duplicate (Ticker, Year) pairs
combined = combined.drop_duplicates(subset=['Ticker', 'Year'])

# Keep only valid Class values (0 or 1)
combined = combined[combined['Class'].isin([0, 1])]
combined['Class'] = combined['Class'].astype(int)

# Coerce all non-meta columns to numeric
meta_cols = ['Ticker', 'Year', 'Sector', 'Class']
numeric_cols = [c for c in combined.columns if c not in meta_cols]
for col in numeric_cols:
    combined[col] = pd.to_numeric(combined[col], errors='coerce')

# Drop rows with zero financial data
combined = combined.dropna(subset=numeric_cols, how='all')





# ─────────────────────────────────────────────────────────────────
# STEP 3 — FEATURE ENGINEERING
# ─────────────────────────────────────────────────────────────────

def profit_tier(x):
    if pd.isna(x):  return 'Unknown'
    if x >= 0.20:   return 'High (≥20%)'
    if x >= 0.10:   return 'Medium (10-20%)'
    if x >= 0:      return 'Low (0-10%)'
    return 'Negative'

def leverage_bucket(x):
    if pd.isna(x):  return 'Unknown'
    if x < 0.5:     return 'Conservative (<0.5x)'
    if x < 1.0:     return 'Moderate (0.5-1x)'
    if x < 2.0:     return 'Elevated (1-2x)'
    return 'High (>2x)'

def growth_label(x):
    if pd.isna(x):  return 'Unknown'
    if x > 0.15:    return 'High Growth (>15%)'
    if x > 0.05:    return 'Moderate (5-15%)'
    if x >= 0:      return 'Flat (0-5%)'
    return 'Declining'

def perf_label(x):
    if pd.isna(x):  return 'Unknown'
    if x > 20:      return 'Strong Outperformer (>20%)'
    if x > 5:       return 'Outperformer (5-20%)'
    if x >= -5:     return 'Neutral (-5% to 5%)'
    if x >= -20:    return 'Underperformer (-5% to -20%)'
    return 'Heavy Decline (<-20%)'

combined['Profit_Margin_Tier']    = combined['Net Profit Margin'].apply(profit_tier)
combined['Leverage_Bucket']       = combined['Debt to Equity'].apply(leverage_bucket)
combined['Revenue_Growth_Label']  = combined['Revenue Growth'].apply(growth_label)
combined['Performance_Label']     = combined['Annual_Price_Change_Pct'].apply(perf_label)
combined['Class_Label']           = combined['Class'].map({1: 'Positive Return', 0: 'Negative/Flat Return'})


# ─────────────────────────────────────────────────────────────────
# STEP 4 — FILTER TO CURATED COMPANIES (80 well-known S&P names)
# 8 per sector × 11 sectors  →  ~400 rows after 5-year expansion
# ─────────────────────────────────────────────────────────────────

curated_tickers = [
    # Technology (10)
    'AAPL', 'MSFT', 'GOOGL', 'META', 'NVDA',
    'INTC', 'ORCL', 'IBM',  'CSCO', 'ADBE',

    # Healthcare (8)
    'JNJ',  'PFE',  'UNH',  'MRK',
    'ABBV', 'ABT',  'AMGN', 'GILD',

    # Financial Services (8)
    'JPM',  'BAC',  'WFC',  'GS',
    'MS',   'BLK',  'AXP',  'C',

    # Consumer Cyclical (8)
    'AMZN', 'HD',   'MCD',  'NKE',
    'SBUX', 'TGT',  'LOW',  'GM',

    # Consumer Defensive (8)
    'PG',   'KO',   'PEP',  'WMT',
    'COST', 'CL',   'MO',   'PM',

    # Energy (8)
    'XOM',  'CVX',  'COP',  'SLB',
    'EOG',  'PSX',  'OXY',  'KMI',

    # Industrials (8)
    'BA',   'MMM',  'GE',   'CAT',
    'HON',  'UPS',  'FDX',  'DE',

    # Communication Services (7)
    'T',    'VZ',   'NFLX', 'DIS',
    'CMCSA','CHTR', 'TMUS',

    # Basic Materials (6)
    'LIN',  'APD',  'ECL',  'NEM',  'FCX',  'PPG',

    # Real Estate (6)
    'AMT',  'PLD',  'CCI',  'SPG',  'EQIX', 'PSA',

    # Utilities (6)
    'NEE',  'DUK',  'SO',   'D',    'AEP',  'EXC',
]

df_filtered = combined[combined['Ticker'].isin(curated_tickers)].copy()

# ── Diagnostic: which tickers were NOT found in the dataset ──
found    = set(df_filtered['Ticker'].unique())
missing  = set(curated_tickers) - found
print(f"\nTickers found   : {len(found)}")
print(f"Tickers missing : {len(missing)}")
if missing:
    print(f"  → Not in dataset: {sorted(missing)}")


# ─────────────────────────────────────────────────────────────────
# STEP 5 — SELECT KEY COLUMNS FOR TABLEAU
# ─────────────────────────────────────────────────────────────────

key_cols = [
    # Identifiers
    'Ticker', 'Year', 'Sector', 'Class', 'Class_Label',

    # Stock performance
    'Annual_Price_Change_Pct', 'Performance_Label',

    # Income Statement
    'Revenue', 'Revenue Growth', 'Revenue_Growth_Label',
    'Gross Profit', 'Operating Income', 'Net Income',
    'EPS', 'EPS Diluted',

    # Margins
    'Gross Margin', 'EBIT Margin', 'EBITDA Margin',
    'Net Profit Margin', 'Profit_Margin_Tier',
    'Free Cash Flow margin',

    # Cash Flow
    'Operating Cash Flow', 'Free Cash Flow', 'Capital Expenditure',

    # Balance Sheet
    'Total assets', 'Total liabilities', 'Total shareholders equity',
    'Cash and short-term investments', 'Total debt', 'Net Debt',

    # Valuation Multiples
    'Market Cap', 'Enterprise Value',
    'PE ratio', 'Price to Sales Ratio',
    'priceToBookRatio', 'Enterprise Value over EBITDA',

    # Returns / Profitability
    'returnOnAssets', 'returnOnEquity',
    'returnOnCapitalEmployed', 'ROIC',

    # Leverage & Liquidity
    'Debt to Equity', 'Debt to Assets', 'Leverage_Bucket',
    'currentRatio', 'quickRatio', 'interestCoverage',

    # Per Share & Dividends
    'Revenue per Share', 'Net Income per Share',
    'Book Value per Share', 'Dividend per Share', 'dividendYield',

    # YoY Growth Rates
    'Gross Profit Growth', 'Net Income Growth', 'EPS Growth',
    'Operating Cash Flow growth', 'Free Cash Flow growth',
]

# Keep only columns that actually exist in the data
key_cols   = [c for c in key_cols if c in df_filtered.columns]
tableau_df = df_filtered[key_cols].copy()

# Sort for clean Tableau experience
tableau_df = tableau_df.sort_values(['Ticker', 'Year']).reset_index(drop=True)

print(f"\nFinal Tableau dataset : {tableau_df.shape[0]} rows × {tableau_df.shape[1]} cols")
print(f"Unique tickers        : {tableau_df['Ticker'].nunique()}")
print(f"Years                 : {sorted(tableau_df['Year'].unique())}")
print(f"\nRows per sector:")
print(tableau_df.groupby('Sector')['Ticker'].nunique().sort_values(ascending=False).to_string())
print(f"\nClass distribution:")
print(tableau_df['Class_Label'].value_counts().to_string())


# ─────────────────────────────────────────────────────────────────
# STEP 6 — EXPORT
# Download will trigger automatically in Colab
# ─────────────────────────────────────────────────────────────────


output_path = '/content/outputs/SP500_Tableau_Final.csv'
tableau_df.to_csv(output_path, index=False)

files.download(output_path)
print(f"\n✅ File downloaded: SP500_Tableau_Final.csv")
print(f"   Ready to drag into Tableau!")